"""
Payment Health Score for the Payment Health Engine.

A deterministic, explainable 0-100 score for a single aggregated time
window, built from four documented components. This score is NOT
generated by an LLM — it's a fixed formula so it is reproducible and
testable.

============================================================
COMPONENT WEIGHTS (chosen, not copied blindly — documented rationale)
============================================================

  success_rate_health   40%  — the single most direct signal of payment
                                 reliability; weighted highest because a
                                 drop in success rate is the thing that
                                 actually costs revenue.
  latency_health         25%  — latency degradation often precedes or
                                 accompanies failures (see the timeout/
                                 network_error correlation in the Phase 1
                                 generator) and matters even when payments
                                 still ultimately succeed (bad UX).
  failure_pattern_health 20%  — distinguishes "normal" failure mix from a
                                 surge in systemic failure types (timeout,
                                 network_error, technical_error), which
                                 tend to indicate infrastructure problems
                                 rather than routine declines.
  volume_health           15%  — lowest weight; volume swings are the
                                 weakest standalone signal (could be
                                 legitimate traffic variation) but a
                                 severe drop can indicate an outage
                                 upstream of the payment funnel, so it's
                                 not ignored either.

These weights sum to 1.0 and were chosen to reflect "how directly does
this metric represent lost revenue / broken payments", not derived from
any dataset fit. They are intentionally simple to keep the score
explainable.

============================================================
COMPONENT FORMULAS (each bounded to [0, 100])
============================================================

  success_rate_health:
    ratio = current_success_rate / baseline_success_rate  (safe: default 1.0)
    score = 100 * min(ratio, 1.0)
    Rationale: performing at or above baseline is "fully healthy" (100);
    below baseline scales down proportionally to the shortfall.

  latency_health:
    ratio = current_latency / baseline_latency  (safe: default 1.0)
    score = 100 when ratio <= 1
          = linearly interpolated to 0 at ratio == LATENCY_RATIO_FLOOR (3.0)
          = 0 when ratio >= LATENCY_RATIO_FLOOR
    Rationale: 3x baseline latency is treated as "as bad as it gets" for
    scoring purposes — chosen because the injected LATENCY_SPIKE and
    BANK_RAIL_DEGRADATION scenarios in the generator use latency
    multipliers up to ~2.2-3.0x.

  failure_pattern_health:
    systemic_rate = timeout_rate + network_error_rate + technical_error_rate
    baseline_systemic_rate = same, from baseline's overall failure_rate
        composition (approximated here via the window's own baseline
        failure_rate scaled by the SAME proportion the window shows,
        since baseline is only tracked at the failure_rate level, not
        per-reason — see "Known limitations").
    delta = systemic_rate - baseline_systemic_rate
    score = 100 when delta <= 0
          = linearly interpolated to 0 at delta == SYSTEMIC_DELTA_FLOOR (0.30)
          = 0 when delta >= SYSTEMIC_DELTA_FLOOR
    Rationale: a 30-percentage-point jump in systemic failure types is
    treated as maximally unhealthy — chosen to match the ~30-40pp jumps
    seen in the injected bank-rail/latency-spike scenarios.

  volume_health:
    ratio = current_volume / baseline_volume  (safe: default 1.0)
    score = 100 when ratio in [0.7, 1.5]  (normal business fluctuation band)
          = linearly degraded outside that band, reaching 0 at ratio <= 0.2
            (a near-total volume collapse) or ratio >= 3.0 (an unexplained
            spike, e.g. a retry storm)
    Rationale: both directions are penalized, but the healthy band is
    wide because legitimate traffic naturally varies window to window.

============================================================
HEALTH STATUS THRESHOLDS (chosen, documented)
============================================================

  health_score >= 80  -> HEALTHY
  health_score >= 50  -> DEGRADED
  health_score <  50  -> CRITICAL

Chosen so that a single dominant component failing hard (e.g. success
rate collapsing to ~50% of baseline, contributing ~20 points from its 40%
weight, with everything else healthy) pulls the score into DEGRADED but
not automatically CRITICAL — CRITICAL requires either a severe hit on the
highest-weighted component or multiple components degrading together.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

from ml.health.features import safe_ratio

SUCCESS_WEIGHT = 0.40
LATENCY_WEIGHT = 0.25
FAILURE_PATTERN_WEIGHT = 0.20
VOLUME_WEIGHT = 0.15

LATENCY_RATIO_FLOOR = 3.0
SYSTEMIC_DELTA_FLOOR = 0.30

VOLUME_HEALTHY_LOW = 0.7
VOLUME_HEALTHY_HIGH = 1.5
VOLUME_FLOOR_LOW = 0.2
VOLUME_FLOOR_HIGH = 3.0

HEALTHY_THRESHOLD = 80.0
DEGRADED_THRESHOLD = 50.0

SYSTEMIC_FAILURE_REASONS = ["timeout_rate", "network_error_rate", "technical_error_rate"]


class HealthStatus(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    CRITICAL = "CRITICAL"


def _clip(value: float, low: float = 0.0, high: float = 100.0) -> float:
    return max(low, min(high, value))


def _linear_falloff(bad_value: float, good_at: float, zero_at: float) -> float:
    """100 when bad_value <= good_at, 0 when bad_value >= zero_at,
    linearly interpolated in between. Assumes zero_at > good_at."""
    if bad_value <= good_at:
        return 100.0
    if bad_value >= zero_at:
        return 0.0
    fraction = (bad_value - good_at) / (zero_at - good_at)
    return 100.0 * (1.0 - fraction)


def success_rate_health(success_rate: float, baseline_success_rate: float) -> float:
    ratio = safe_ratio(success_rate, baseline_success_rate, default=1.0)
    return _clip(100.0 * min(ratio, 1.0))


def latency_health(avg_latency_ms: float, baseline_latency_ms: float) -> float:
    ratio = safe_ratio(avg_latency_ms, baseline_latency_ms, default=1.0)
    return _clip(_linear_falloff(ratio, good_at=1.0, zero_at=LATENCY_RATIO_FLOOR))


def failure_pattern_health(
    window_failure_rate: float,
    window_systemic_component_rates: dict[str, float],
    baseline_failure_rate: float,
) -> float:
    """`window_systemic_component_rates` are the window's own
    timeout_rate/network_error_rate/technical_error_rate (fractions of all
    transactions). The baseline systemic rate is approximated by scaling
    the baseline's overall failure_rate by the window's own systemic
    share of its failures — see module docstring "Known limitations" for
    why this approximation is used instead of a per-reason baseline.
    """
    window_systemic_rate = sum(window_systemic_component_rates.values())

    if window_failure_rate > 1e-9:
        systemic_share_of_failures = window_systemic_rate / window_failure_rate
    else:
        systemic_share_of_failures = 0.0

    baseline_systemic_rate = baseline_failure_rate * systemic_share_of_failures
    delta = window_systemic_rate - baseline_systemic_rate
    return _clip(_linear_falloff(delta, good_at=0.0, zero_at=SYSTEMIC_DELTA_FLOOR))


def volume_health(transaction_count: float, baseline_volume: float) -> float:
    ratio = safe_ratio(transaction_count, baseline_volume, default=1.0)
    if VOLUME_HEALTHY_LOW <= ratio <= VOLUME_HEALTHY_HIGH:
        return 100.0
    if ratio < VOLUME_HEALTHY_LOW:
        return _clip(_linear_falloff(-ratio, good_at=-VOLUME_HEALTHY_LOW, zero_at=-VOLUME_FLOOR_LOW))
    return _clip(_linear_falloff(ratio, good_at=VOLUME_HEALTHY_HIGH, zero_at=VOLUME_FLOOR_HIGH))


def status_from_score(score: float) -> HealthStatus:
    if score >= HEALTHY_THRESHOLD:
        return HealthStatus.HEALTHY
    if score >= DEGRADED_THRESHOLD:
        return HealthStatus.DEGRADED
    return HealthStatus.CRITICAL


@dataclass
class HealthScoreResult:
    score: float
    status: HealthStatus
    components: dict[str, float] = field(default_factory=dict)

    def as_dict(self) -> dict:
        return {"score": self.score, "status": self.status.value, "components": self.components}


def compute_health_score(row: dict) -> HealthScoreResult:
    """Compute the health score for one deviation-feature-enriched row
    (a dict or pandas Series with the columns produced by
    `ml.health.features.add_deviation_features`).
    """
    sr_health = success_rate_health(row["success_rate"], row["baseline_success_rate"])
    lat_health = latency_health(row["average_latency_ms"], row["baseline_average_latency_ms"])
    fp_health = failure_pattern_health(
        window_failure_rate=row["failure_rate"],
        window_systemic_component_rates={k: row[k] for k in SYSTEMIC_FAILURE_REASONS},
        baseline_failure_rate=row["baseline_failure_rate"],
    )
    vol_health = volume_health(row["transaction_count"], row["baseline_transaction_count"])

    score = (
        SUCCESS_WEIGHT * sr_health
        + LATENCY_WEIGHT * lat_health
        + FAILURE_PATTERN_WEIGHT * fp_health
        + VOLUME_WEIGHT * vol_health
    )
    score = _clip(score)

    components = {
        "success_rate_health": sr_health,
        "latency_health": lat_health,
        "failure_pattern_health": fp_health,
        "volume_health": vol_health,
    }
    return HealthScoreResult(score=score, status=status_from_score(score), components=components)
